version: '3.8'

services:
  # Angular frontend service
  angular_frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./order-fronted-app:/app
    ports:
      - "4200:80"
    networks:
      - lunch

networks:
  lunch:
    external: true
